language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: czliA3OBqAKorhXKDuT4d3rN46PJMlyoGaHV4XLjxWi/zl1AkuR0/AbUecbZpuZpRJwu3sLnOrrbT7ATG7cbxg06D8aihgfela39d3wme3VPaCdLZMEG0z28aey+5XeZTd+UIFVOT/I7xPOVewweyhdjJn7ZaEdEA+KhZVNetV/Bc6/ooYv/goGv6X8m66FDJXS4ywtf8EsFfu80aphWtOHXrRskGOSnenf8RAeWhLuKWxOM87ZAv8h9KL0sMIDTJZnQnZc42am3L13pMyX32h1/lu//f8y9O21dB+LhdP2zXyq0ZgcsLR7GJFW/0CFgzUwaiey3HR3MJSkJTyyimD7BhYBDaYt93bkcJH7W/KoYu7ic8T3yyDTVSXiESzdVLrhnEz2UXczOCGLl25yxwKo+BpswPSepIefbkDIXAN/cPcxQpr6Oca5EOn/i9Ail1YHJEZYshzEr04JlcpHVYej4BjrKJjsJWrpVR70oclrimnTGdSdNQmubOKbM8BjK22Ugc6X/FC9Cy9Pq5BuF3wdKW5/UVQf3vCztqCHZENBhvsBYOXkynKpsD80mQyrPn+SzlrqsMaNzhwbkeJpl/LY00bPFRowN4BpRCPua4UTsRzHrxXwQ4oY+VKYIH7H804fkYbYl3emf4QtV/wFrfUGd40u6nbTyFYwOHycAk6w=
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out id_rsa -d
