language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out identity -d
env:
  global:
    secure: avyilkBUh3uffF+BfzJ/dc4Ed9lRxNsK4USy+uNJyCgHXyyOtuI8gvkuq6W4R4YB+NYRmkB/n14PoazECTsJ3s+otRBMwGIbbBaKE+fO2Hq/OOmUvZBMsPBr07PwF5LmSU77o38L9inkI7SoDMRHMcIaLwpjE79fZiSySiRfNoE+TbIFFDX/LuNNxw6II3XKVfMsftRexCQXE1fVhuDybjx7OfMAeWq0Lo60ZDopBI6PuUJ4CEQ/G0WByc5ZHUAC0avJmQUsO8rQBmwU0buIweN0fzaEq0jQ5Swr8i+jAE9mvZWCWrC+A96w1jxRH1pOVdzYdffNotrR7HR8Ws62zlHSo7MJBDByUiPeaCph7Ow83rWOEHJVcbsEFFDFkI2ssnLEoq9lpcV5OsNMBpwAYqgq3s6eKgrW1bCJ67EyOtObcvxnTFU50dhLI5xozIPK4jQ8japspfmZ3Y/9cP+EVDi+PJvLF1QxZeZsE3eeShbheRUeMtohatk109MHfCWlYYad6utbO/dpn8BolxYJ15Dxw4t/kYywWtvjztfb9oRpud1UW+7LADixkS6uWl92QeX4sfj0tcew/5f2Iv3bWInw4nCykAeoCNXR60nXpybmJf5AXRKsz0vbVxLPry3+gNU5JHjeaYxHooIFq7U5wXxQ904nYwhVS/RqYhq/vr4=
