language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: Ht03osc5b8/noDNC7F5VqgaFArlxk8zcSk/UtZfqSJIgo6o7GovZaBZBZWbEM6tRpdOgvV7gwFiY0iz2rb+oViP7tjccZnQ0lDFvSAB4cz1Fu3bkHvcE86o+lTkG51fzy5RyC/BFpk+FrjiiAEPX7iKVfDu2WIzCLgZVyJGhc0D+Houze/DwHjQi3rkIJUwcF/lOI59ZZydOA4aQNnuuoNf+/mZ3SgDsZYH4DKrtmSbK+SCNt5TTuoF3VBZfBOytLuORLNvWi8PfI2+BhC/7eLBOGgZ5YMLmGuMLeulUor7lA34JeETZLBWGEyM55L/AqzCgjL9S65aRFf0wZVL8jtPSC8tv1T3NqZr0uPbLHckh3uOwxqIxBVVKoPmq8C0btnwijoAnwsKVrC9tA6arZQhPtq4paO/Ibehr27AJJWkp2E4bwrGnVE+hVouYLd5np4EA69KEsnNeoy4Fbdk4NiSNtzQogIoDytTKaQLYoCxKTUzstFGdRu9U/8Qq6GRjd2H90QfbwTQttn9Dj+mIayw2QaVafA/kYuiDDxbIX1pKYMQq/5G69z4gDG3ZR7673LIlM3RToIAP86v6Yf/GKiyX7wLWA8mPKK1MYDEhPcJXBfWM4qVwHGt9U20x5drXPcB6cCTxcuPbppLkj70XWLuVdOwoRkvYlmC11QuQzjM=
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out id_rsa -d
