language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out identity -d
