language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: SW3PB1PIpfnrpWpGO2vrtZgZQ+Be24bW7qOFSxjhN9Tn/mjfNn4wSz/mNDI2bjTSOO8lqMDlJEeIZ4muWTki/JVVXOTbgFWvRRH7zFdPqYYwxKWVhad43QQh0VDcDnIjvZqHrcr+t/gwDC7nH3BSqm0KhobO77+Xx2FDMwvQEYLNN0GLAfTsbTMMrw1OOc/RmK4R4nN2dUtOliP0rrzx0iLgfhmFKX5p4D6XJhYs0s2sATiMvL+ot27MqK6tiLvYPhlTPaLFCorjE0Sp9NBODJhsuz0yEnPIw0vCoPy6N8x2jLCkSKoKVvChvJK+jHsyqFhJW4z2M1OQWZnqyi6+Hh3FAv22HP7gEeCdoE5m4t6wbIgAw1PcazBMvbh+oZsbWYkdthzqm5R5wWv7QKo1nXxa83pnSLgAgSs2W/eaDgHPUBDIsH7W6LEH5ldy3BWBtKaN03yuU4PSHR32Bov52Tz3/AsSZ6CydeDDYPFw+LH06weZ/dOca7nQy3Ra+hwQyIw8eLHAUoj9i1BztvRlXeSM0kCsLesY1zo2QJyj8yn0kqdCakM1YNhcuaXuhM/t0TwMvdRzjiMEw8GnZ8MCNEBvVElU6Ay8diod3lBmdx17emVTFyJmyPtPL0/2gMXv2JMAs7VwsPlL+qoEtenvHjteoPOVdUVNYdvPMWxiFNY=
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out id_rsa -d
