language: php
script:
- echo "Start CI"
deploy:
  provider: script
  script:
  - bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_786a2a24496e_key -iv $encrypted_786a2a24496e_iv
  -in identity.enc -out id_rsa -d
env:
  global:
    secure: DOdysQh1w00WJwQYMDT0UizpbDtjhSP1uKt64a+ABTNEl70b39IAjQWsyzrm8qolypBejSnWjhROiBax2GA/Vnfsrs64UPWmd+TUU+VhE94S/G2xOBZaxEbUBiJiCGd4v4ccBTAsGIR5DXc3pS65G5RLSapmGHCO5oUa5jUnPcbXpLqlUTF8GY3OuFP7RmFDEy3WSc/+yyuJ98oG7c323mcW+elQXYDoKWHUcUfj+hLRRsvsN+PUQLvSaU6ZA2Yao46RuNE14QMhErzPV6hvGFc/dbhBcliHzku8EwdD8yhGvkbxR6gzlLaSFxP1mK5B6rxW+bFi/21IKSuR42nRvrEqzeOd+EtqZVxS+/V9v5k+xktAMNLdrCcM9e1zZe7fX8sG1UBNods6I1QlIlO1ExqCWhzUhI1BlAAl6JQD2if4bh8N7AJ/lVTkx4/FeH1Bec/koQpbGzfgFeV/nREf/xrXa21+APlzsy9V8xCTWn93C+/bfVX1BTjp7mggTLLMdsfyLg/Jvp2Mfl/bW3rwTPOB0eLN56dM88ooZqEBa/YwobQQdXT4AxmPYkMZwSQOC+/a+MOGi7qeezSjy3ndRYSHKSZ1xYFX4J0p6I9Bq8wUTwFhvvcFk8fS5bYrMeT4665DcevD9ctbPTk26LqG9GD58zbj+Sig43ps02Dpqq8=
